### ISSUE TITLE
`ingress rules` should leave under the module's `spec` section

### ISSUE THREAD

**Issue by ghen** [score-spec/score-humanitec#10]
Workloads created from score spec have empty ingress rules section in Humanitec.

---

Input `score.yaml`:

```yaml
apiVersion: score.dev/v1b1

metadata:
  name: whalesay

service:
  ports:
   www:
     port: 8080
     targetPort: 8080

containers:
  hello:
    image: carolynvs/whalesayd:v0.1.1

resources:
  dns:
    type: dns
```

Additional `humanitec.score.yaml`:

```yaml
apiVersion: humanitec.org/v1b1

service:
  routes:
    "http":
      "/":
        from: ${resources.dns}
        type: exact
        port: 8080
```

Using `score-humanitec` CLI `v0.1.0`:

```console
score-humanitec draft -f score.yaml --org ${HUMANITEC_ORG} --env ${HUMANITEC_ENV} --app ${HUMANITEC_APP} --token ${HUMANITEC_TOKEN}
```

Delta produced by the tool:

```json
{
  "id": "ce685af14704045eaaaf96aab09d2b9e88c15df5",
  "metadata": {
    "env_id": "development",
    "name": "Auto-generated (SCORE)",
    "url": "https://api.humanitec.io/orgs/clearcode/apps/whale/envs/development/draft/ce685af14704045eaaaf96aab09d2b9e88c15df5",
    "created_by": "s-9b4c1a52-7679-4e67-8a34-90e2ca3d177f",
    "created_at": "2022-11-07T07:08:31.752355445Z",
    "last_modified_at": "2022-11-07T07:08:31.752355445Z"
  },
  "modules": {
    "add": {
      "whalesay": {
        "externals": {
          "dns": {
            "type": "dns"
          }
        },
        "ingress": {
          "rules": {
            "externals.dns": {
              "http": {
                "/": {
                  "port": 8080,
                  "type": "exact"
                }
              }
            }
          }
        },
        "profile": "humanitec/default-module",
        "spec": {
          "containers": {
            "hello": {
              "id": "hello",
              "image": "carolynvs/whalesayd:v0.1.1"
            }
          },
          "service": {
            "ports": {
              "www": {
                "container_port": 8080,
                "protocol": "TCP",
                "service_port": 8080
              }
            }
          }
        }
      }
    }
  }
}
```

Using this delta to create a workload in Humanitec leads to empty `ingress rules` section on the UI.

---

Comparing to the PATCH request contents sent to Humanitec API by the UI, `ingress rules` should leave under the `spec` section in the `module` definition:

```json
[{
	"modules": {
		"update": {
			"test-ingress": [{
				"op": "add",
				"path": "/spec/ingress/rules/externals.dns/http/~1",
				"value": {
					"type": "prefix",
					"port": 80
				}
			}]
		}
	}
}]
```
