### ISSUE TITLE
[feature]: Custom workload profiles features specs support

### ISSUE THREAD

**Issue by ghen** [score-spec/score-humanitec#19]
### Problem

At present Score spec translates to a default module structure based on `humanitec/default-module` built-in workload profile. In many situation user wants to use different workload profile. For example `humanitec/default-cronjob` or `my-org/frontend-service`.

Moreover, custom workload profiles may use additional features, that are not covered in `humanitec/default-module`. The user wants to provide contents for such custom features and inject those into the deployment delta spec produced by the CLI tool.

### Example

For example, a simple `score.yaml` for the workload:
```yaml
apiVersion: score.sh/v1b1

metadata:
  name: web-app

service:
  ports:
    www:
      port: 80

containers:
  web-app:
    image: nginx
    files:
      - target: /usr/share/nginx/html/index.html
        mode: "644"
        content: ["${resources.env.MESSAGE}"]

resources:
  env:
    type: environment
    properties:
      MESSAGE:
        type: string
  dns:
    type: dns
```

Translates into the following deployment delta JSON:

```json
{
    "metadata": {...},
    "modules": {
        "add": {
            "web-app": {...}
        }
    }
}
```

The `web-app` module definition JSON:

```json
{
    "web-app": {
        "externals": {
            "dns": {
                "type": "dns"
            }
        },

        "profile": "humanitec/default-module",

        "spec": {
            "containers": {
                "hello": {
                    "files": {
                        "/usr/share/nginx/html/index.html": {
                            "mode": "644",
                            "value": "${values.MESSAGE}"
                        }
                    },
                    "id": "hello",
                    "image": "nginx"
                }
            },
            "service": {
                "ports": {
                    "www": {
                        "container_port": 80,
                        "protocol": "TCP",
                        "service_port": 80
                    }
                }
            }
        }
    }
}
```

The `spec` section for the `humanitec/default-module` supports these features:
* containers
* service
* labels
* ingress

There is no way to provide specification for additional features, such as `labels` and `ingress`.

### Example 2

Another good example would be a built-in `humanitec/default-cronjob` workload profile and its `schedules` feature:

```json
{
    "background-cron": {
        "profile": "humanitec/default-cronjob",
        "spec": {
            "containers": {
                "busybox": {
                    "image": "odise/busybox-curl:stable"
                }
            },
            "schedules": {
                "every-1-min": {
                    "containers": {
                        "busybox": {
                            "args": ["-c", "curl -X POST http://some-service/start-job"],
                            "command": ["/bin/sh"]
                        }
                    },
                    "schedule": "* * * * *"
                }
            }
        }
    }
}
```

### Proposal

Proposal is to allow the user to override the workload `profile` being used, and to include additional features in Humanitec's extension file `humanitec.score.yaml`:

```yaml
apiVersion: humanitec.org/v1b1

profile: "humanitec/default-module"
spec:
  "lables":
    "tags.datadoghq.com/env": "${resources.env.DATADOG_ENV}"
  "ingress":
    rules:
      "${resources.dns}":
        http:
          "/":
            type: prefix
            port: 80
```

As the result, the output `web-app` module definition JSON would include additional `labels` and `ingress` sections:

```json
{
    "web-app": {
        "externals": { ... },

        "profile": "humanitec/default-module",

        "spec": {
            "containers": { ... },
            "service": { ... },
            "labels": {
                "tags.datadoghq.com/env": "${values.DATADOG_ENV}"
            },
            "ingress": {
                "rules": {
                    "externals.dns": {
                        "http": {
                            "/": {
                                "port": 80,
                                "type": "prefix"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

### Requirements

Humanitec's extensions file (`humanitec.score.yaml`) schema:

```yaml
apiVersion: [string]

profile: [string]
spec:
  [string]: Object

resources:
  [string]: Object
```

The new properties are:
* `profile` is a custom workload profile name. Default value is: `humanitec/default-module`.
* `spec` is a map of features to inject into the final workload module `spec`:
  * `key` is a [JSON path](https://jsonpath.com/), relative to the `spec` section root. For example: `labels`
  * `value` is an object that would be injected, **replacing** any existent content of the node at the path specified by the key.

**Note:** All valid patterns in features objects string properties and string values are parsed and substituted following the same rules as substitution patterns used for the main Score spec.
