### ISSUE TITLE
sub_path for volume is missing

### ISSUE THREAD

**Issue by sujaya-sys** [score-spec/score-humanitec#47]
| sub_path  | String  | Specifies a sub-directory in the volume to mount. Must be a [relative path](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath). |

https://developer.humanitec.com/platform-orchestrator/reference/workload-profiles/features/#volume-mounts 

```
    volumes:
      - source: ${resources.rstudio-pv}
        target: /data/humanitec
        read_only: false
        sub_path: thing

       sub_path: thing
```

It doesn't seem to work/be on the schema

```
   volumes:                                # (Optional) Specifies volumes to mount
    - source: ${resources.data}             #    - External volume reference
      path: sub/path                        #    - (Optional) Sub path in the volume
      target: /mnt/data                     #    - Target mount path on the container
      read_only: true                       #    - (Optional) Mount as read-only
```

**Comment by sujaya-sys** [comment]
We need to think about things that change the public score spec. In the meantime we can use the humanitec extensions file:

```

...
spec:
  volumes:
    volume-id:
      sub_path: thing
```
