### ISSUE TITLE
[feature request] Provide docker image for each release

### ISSUE THREAD

**Issue by Noordsestern** [score-spec/score-humanitec#49]
**Is your feature request related to a problem?**
I want to use `score-humanitec` in my pipelines. That requires a docker image as execution environment for the deploy job. Example in gitlab (the value in `image` that i would like to use):

```yaml
Deploy Camunda 7 With score:
  stage: deploy
  image: ghrc.io/score/score-humanitec:0.6.0
  script: 
    - score-humanitec delta .......  --deploy  
```

Right now I have to build the base image myself or install score-humanitec in each pipeline execution.

**Describe the solution you'd like**
Easiest would be, if docker image is published together with each release.
