### ISSUE TITLE
[bug] placeholders are not processed in resource params

### ISSUE THREAD

**Issue by chrishumanitec** [score-spec/score-humanitec#54]
**Describe the bug**
placeholders are not processed in resource params

**To Reproduce**
1. Use the following score file:
```
apiVersion: score.dev/v1b1
metadata:
  name: hello-world

containers:
  container-id:
    image: nginx

resources:
  my-dns:
    type: dns
  my-route:
    type: route
    params:
      host: ${resources.my-dns.host}
      path: /products
      port: 80
```
3. Deploy it

**Expected behavior**
Deployment works

**Actual behaviour**
Humanitec reports the following error:
> Driver parameters invalid
> 'ip_address', 'ipv6_address' or 'name' should be specified in the resource parameters: resource definition default-humanitec-dns - resource type dns

**Analysis**
The generated deployment set includes the untransformed placeholder `${resources.my-dns-host}` instead of `${modules.hello-world.externals.dns.host}`
